services:

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"     # WEB ENTRYPOINT | HTTP/80
      - "443:443"   # WEBSECURE ENTRYPOINT | HTTPS/443
      - "8080:8080" # TRAEFIK ENTRYPOINT | API Dashboard (enabled by --api.insecure=true)
    env_file:
      - .env
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}             # Account email
      - CF_API_KEY=${CF_API_KEY}                 # API Key
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}     # API token with DNS:Edit permission
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
    networks:
      - traefik

  whoami:
    image: traefik/whoami
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.whoami.rule=Host(`whoami.earles.lab`)
      - traefik.http.routers.whoami.entrypoints=websecure
      # - traefik.http.routers.whoami.tls
      # - traefik.http.routers.whoami.tls.certresolver=staging
      # - traefik.http.routers.whoami.tls.certresolver=production
      # - traefik.http.routers.whoami.middlewares=auth
      # - traefik.http.middlewares.auth.basicauth.usersfile=/etc/traefik/conf/authorizedusers # Use htpasswd to generate user:hash
    networks:
      - traefik
networks:
  traefik:
    external: true