services:
  n8n:
    image: 'docker.n8n.io/n8nio/n8n'
    container_name: n8n
    restart: unless-stopped
    volumes:
      - ./data:/home/node/.n8n
    # ports:
    #   - '5678:5678'
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.n8n.rule=Host(`n8n.internal.earles.io`)
      - traefik.http.routers.n8n.entrypoints=websecure
      - traefik.http.routers.n8n.tls.certresolver=production

networks:
  traefik:
    external: true