services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:latest
    container_name: changedetection
    hostname: changedetection
    restart: unless-stopped
    volumes:
      - ./data:/datastore
    environment:
      - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000
    networks:
      - traefik
      - backend
    depends_on:
      playwright-chrome:
            condition: service_started
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.changedetection.rule=Host(`changedetection.internal.earles.io`)
      - traefik.http.routers.changedetection.entrypoints=websecure
      - traefik.http.routers.changedetection.tls.certresolver=production

  playwright-chrome:
    image: dgtlmoon/sockpuppetbrowser:latest
    container_name: changedetection-playwright
    hostname: playwright-chrome
    restart: unless-stopped
    #  cap_add:
    #      - SYS_ADMIN
# SYS_ADMIN might be too much, but it can be needed on your platform https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-gitlabci
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - MAX_CONCURRENT_CHROME_PROCESSES=10
    networks:
      - backend
networks:
  traefik:
    external: true
  backend: