services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actual
    restart: unless-stopped
    volumes:
      - ./data:/data
    # ports:
    #   - '5006:5006'
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.budget.rule=Host(`budget.internal.earles.io`)
      - traefik.http.routers.budget.entrypoints=websecure
      - traefik.http.routers.budget.tls.certresolver=production

networks:
  traefik:
    external: true