services:
  app:
    image: fireflyiii/core:latest
    container_name: firefly-core
    hostname: app
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./upload:/var/www/html/storage/upload
    # ports:
    #   - 80:8080
    networks:
      - traefik
      - backend
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.firefly.rule=Host(`firefly.internal.earles.io`)
      - traefik.http.routers.firefly.entrypoints=websecure
      - traefik.http.routers.firefly.tls.certresolver=production

  db:
    image: mariadb:lts
    container_name: firefly-db
    hostname: db
    restart: unless-stopped
    env_file: .db.env
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - backend

  importer:
    image: fireflyiii/data-importer:latest
    container_name: firefly_iii_importer
    hostname: importer
    restart: unless-stopped
    env_file: .importer.env
    # ports:
    #   - '81:8080'
    networks:
      - traefik
      - backend
    depends_on:
      - app
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.firefly-importer.rule=Host(`firefly-importer.internal.earles.io`)
      - traefik.http.routers.firefly-importer.entrypoints=websecure
      - traefik.http.routers.firefly-importer.tls.certresolver=production

  cron:
    image: alpine
    container_name: firefly-cron
    restart: unless-stopped
    env_file: .env
    networks:
      - backend
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    command: sh -c "
      apk add tzdata
      && ln -s /usr/share/zoneinfo/${TZ} /etc/localtime
      | echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/CnTyYrf6dN6jnZGjPz9zScou4JawHJt4;echo\"
      | crontab -
      && crond -f -L /dev/stdout"

# volumes:
#    firefly_iii_upload:
#    firefly_iii_db:

networks:
  # firefly_iii:
  #   driver: bridge
  traefik:
    external: true
  backend:
    external: false