services:
  vault:
    image: hashicorp/vault
    container_name: hashicorp-vault
    restart: unless-stopped
    env_file:
    - .env
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_API_ADDR=${VAULT_API_ADDR}
      - VAULT_ADDRESS=${VAULT_ADDRESS}
      - VAULT_TOKEN=${VAULT_TOKEN}
      - VAULT_UI=true
    networks:
      - traefik
    volumes:
      - ./logs:/vault/logs/:rw
      - ./data:/vault/data/:rw
      - ./config:/vault/config/:rw
      - ./certs:/certs/:rw
      - ./file:/vault/file/:rw
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config /vault/config/config.hcl
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.vault.rule=Host(`vault.internal.earles.io`)
      - traefik.http.routers.vault.entrypoints=websecure
      - traefik.http.routers.vault.tls.certresolver=production
      - traefik.http.services.vault.loadbalancer.server.port=8200
      - traefik.http.services.vault.loadbalancer.server.scheme=https
networks:
  traefik:
    external: true