services:
  uptime:
    image: louislam/uptime-kuma:1
    container_name: uptimekuma
    restart: unless-stopped
    # env_file:
    #   - .env
    volumes:
      - ./data:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime.rule=Host(`uptime.internal.earles.io`)
      - traefik.http.routers.uptime.entrypoints=websecure
      - traefik.http.routers.uptime.tls.certresolver=production
    networks:
      - traefik

networks:
  traefik:
    external: true