---
- name: Install Hugo and prerequisites
  hosts: all
  become: yes
  vars:
    required_packages:
      - curl
      - git
      - golang-go
      - npm
      - snapd
  
  tasks:
    - name: Update apt cache and install packages
      apt:
        name: "{{ required_packages }}"
        state: present
        update_cache: yes
        cache_valid_time: 3600
      register: package_install
      retries: 3
      delay: 5
      until: package_install is succeeded

    - name: Ensure snapd is started and enabled
      systemd:
        name: snapd
        state: started
        enabled: yes

    - name: Install Hugo via snap
      snap:
        name: hugo
        channel: latest/stable
      register: hugo_install
      retries: 2
      delay: 10
      until: hugo_install is succeeded

    - name: Install sass globally via npm
      npm:
        name: sass
        global: yes
        state: present
      register: sass_install
      retries: 2
      delay: 5
      until: sass_install is succeeded

    - name: Verify Hugo installation
      command: hugo version
      register: hugo_version
      changed_when: false
      failed_when: hugo_version.rc != 0