services:
  vikunja:
    image: vikunja/vikunja
    container_name: vikunja
    restart: unless-stopped
    environment:
      VIKUNJA_SERVICE_PUBLICURL: https://vikunja.internal.earles.io
      VIKUNJA_DATABASE_PATH: /db/vikunja.db # SQLITE
      VIKUNJA_SERVICE_JWTSECRET: ${JWT_SECRET}
      # VIKUNJA_DATABASE_HOST: db
      # VIKUNJA_DATABASE_PASSWORD: changeme
      # VIKUNJA_DATABASE_TYPE: mysql
      # VIKUNJA_DATABASE_USER: vikunja
      # VIKUNJA_DATABASE_DATABASE: vikunja
    volumes:
      - ./files:/app/vikunja/files
      - ./db:/db
    networks:
      - traefik
      # - backend
    # depends_on:
    #   db:
    #     condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.vikunja.rule=Host(`vikunja.internal.earles.io`)
      - traefik.http.routers.vikunja.entrypoints=websecure
      - traefik.http.routers.vikunja.tls.certResolver=production
networks:
  traefik:
    external: true

# Optional MySQL database - uncomment to use MySQL instead of SQLite
#  db:
#    image: mariadb:10
#    container_name: vikunja-db
#    restart: unless-stopped
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#    environment:
#      MYSQL_ROOT_PASSWORD: supersupersecret
#      MYSQL_USER: vikunja
#      MYSQL_PASSWORD: changeme
#      MYSQL_DATABASE: vikunja
#    volumes:
#      - ./db:/var/lib/mysql
#    healthcheck:
#      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"]
#      interval: 2s
#      start_period: 30s