services:
  vikunja:
    image: vikunja/vikunja
    container_name: vikunja
    environment:
      VIKUNJA_SERVICE_PUBLICURL: https://vikunja.internal.earles.io
      VIKUNJA_DATABASE_PATH: /db/vikunja.db #SQLITE
      # VIKUNJA_DATABASE_HOST: db
      # VIKUNJA_DATABASE_PASSWORD: changeme
      # VIKUNJA_DATABASE_TYPE: mysql
      # VIKUNJA_DATABASE_USER: vikunja
      # VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: ${JWT_SECRET}
    volumes: 
      - ./files:/app/vikunja/files
      - ./db:/db
    networks:
      - traefik
      # - backend
    # depends_on:
    #   db:
    #     condition: service_healthy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.vikunja.rule=Host(`vikunja.internal.earles.io`)"
      - "traefik.http.routers.vikunja.entrypoints=websecure"
      - "traefik.http.routers.vikunja.tls.certResolver=production"
  # db:
  #   image: mariadb:10
  #   command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #   environment:
  #     MYSQL_ROOT_PASSWORD: supersupersecret 
  #     MYSQL_USER: vikunja
  #     MYSQL_PASSWORD: changeme
  #     MYSQL_DATABASE: vikunja
  #   volumes:
  #     - ./db:/var/lib/mysql
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"]
  #     interval: 2s
  #     start_period: 30s

networks:
  traefik:
    external: true



  # vikunja:
  #   image: vikunja/vikunja
  #   container_name: vikunja
  #   environment:
  #     VIKUNJA_SERVICE_JWTSECRET: <a super secure random secret>
  #     VIKUNJA_SERVICE_PUBLICURL: http://<your public frontend url with slash>/
  #     # Note the default path is /app/vikunja/vikunja.db.
  #     # This config variable moves it to a different folder so you can use a volume and 
  #     # store the database file outside the container so state is persisted even if the container is destroyed.
  #     VIKUNJA_DATABASE_PATH: /db/vikunja.db
  #   ports:
  #     - 3456:3456
  #   volumes:
  #     - ./files:/app/vikunja/files
  #     - ./db:/db
  #   restart: unless-stopped