services:
  gatus:
    image: twinproduction/gatus:latest
    container_name: gatus
    restart: unless-stopped
    environment:
      - GATUS_CONFIG_PATH=/config/
    volumes:
      - ./config:/config/
      - ./data:/data/
    # ports:
    #   - 8080:8080
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.gatus.rule=Host(`gatus.internal.earles.io`)
      - traefik.http.routers.gatus.entrypoints=websecure
      - traefik.http.routers.gatus.tls.certresolver=production
networks:
  traefik:
    external: true