services:
  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm
    restart: unless-stopped
#    ports:
#      - "3001:3001"
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.anythingllm.rule=Host(`anythingllm.internal.earles.io`)
      - traefik.http.routers.anythingllm.entrypoints=websecure
      - traefik.http.routers.anythingllm.tls.certresolver=production
      - traefik.http.routers.anythingllm.service=anythingllm
      - traefik.http.services.anythingllm.loadbalancer.server.port=3001
#      - traefik.http.services.anythingllm.loadbalancer.passHostHeader=false
    # cap_add:
    #   - SYS_ADMIN
    environment:
    # Adjust for your environment
      - STORAGE_DIR=/app/server/storage
      - JWT_SECRET=${JWT_SECRET}
      # - LLM_PROVIDER='openai'
      # - OPEN_AI_KEY=${OPENAI_API_KEY}
      # - OPEN_MODEL_PREF='gpt-4o'
      - LLM_PROVIDER='openrouter'
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL_PREF='openrouter/auto'
      # - LLM_PROVIDER=ollama
      # - OLLAMA_BASE_PATH=http://127.0.0.1:11434
      # - OLLAMA_MODEL_PREF=llama2
      # - OLLAMA_MODEL_TOKEN_LIMIT=4096
      # - EMBEDDING_ENGINE=ollama
      # - EMBEDDING_BASE_PATH=http://127.0.0.1:11434
      # - EMBEDDING_MODEL_PREF=nomic-embed-text:latest
      # - EMBEDDING_MODEL_MAX_CHUNK_LENGTH=8192
      - VECTOR_DB=lancedb
      # - WHISPER_PROVIDER=local
      - TTS_PROVIDER=native
      - PASSWORDMINCHAR=8
      # Add any other keys here for services or settings
      # you can find in the docker/.env.example file
    volumes:
      # - ./data:/app/server/storage
        - anythingllm_storage:/app/server/storage

networks:
  traefik:
    external: true

volumes:
  anythingllm_storage:
    # driver: local
    # driver_opts:
    #   type: none
      # o: bind
      # device: /path/on/local/disk