services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DEFAULT_WORKSPACE=/config/workspace #optional
      # - PASSWORD=password #optional
      # - HASHED_PASSWORD= #optional
      # - SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
    volumes:
      - ./config:/config
    # ports:
    #   - 8443:8443
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.dev.rule=Host(`dev.internal.earles.io`)
      - traefik.http.routers.dev.entrypoints=websecure
      - traefik.http.routers.dev.tls.certresolver=production

networks:
  traefik:
    external: true