services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.internal.earles.io`)
      - traefik.http.routers.vaultwarden.entrypoints=websecure
      - traefik.http.routers.vaultwarden.tls.certresolver=production
    networks:
      - traefik

  vaultwarden-backup:
    image: bruceforce/vaultwarden-backup
    container_name: vaultwarden-backup
    restart: unless-stopped
    init: true
    depends_on:
      - vaultwarden
    volumes:
      - ./data:/data/
      # - vw_backup:/backup/ # Used temporarily while NAS was down for PSU 03-14-2026 thru 03-18-2026
      - /mnt/documents/vw_backup:/backup/ # Was disabled while NAS was down for PSU 03-14-2026 thru 03-18-2026
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    environment:
      # - DB_FILE=/data/db.sqlite3
      - BACKUP_DIR=/backup/
      - CRON_TIME=0 5 * * * # EVERY DAY 5am
      - TIMESTAMP=true
      - DELETE_AFTER=30
      - UID=1000
      - GID=1000

  vaultwarden-rclone:
    image: rclone/rclone:latest
    container_name: vaultwarden-rclone
    restart: unless-stopped
    depends_on:
      - vaultwarden-backup
    volumes:
      # - vw_backup:/backup:ro # Used temporarily while NAS was down for PSU 03-14 thru 03-18
      - /mnt/documents/vw_backup:/backup:ro
      - ./rclone.conf:/config/rclone/rclone.conf:ro  # B2 earles-vw-backup
    entrypoint: /bin/sh
    command:
      - -c
      - "echo '15 5 * * * rclone sync /backup b2:earles-vw-backup/vw-backup/' > /etc/crontabs/root && crond -f -l 8"

# volumes:
#   vw_backup:

networks:
  traefik:
    external: true