services:

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"     # Ingress HTTP
      - "443:443"   # Ingress HTTPS
      - "8080:8080" # API Dashboard (enabled by --api.insecure=true)
    env_file:
      - .env
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}             # Account email
      - CF_API_KEY=${CF_API_KEY}                 # API Key
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}     # API token with DNS:Edit permission
      # - CF_ZONE_API_TOKEN=${CF_ZONE_API_TOKEN} # API token with Zone:Read permission | Not necessary if CF_DNS_API_TOKEN has both permissions
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
      - ./logs/:/logs/:rw
    networks:
      - traefik

  whoami:
    image: traefik/whoami
    container_name: whoami
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.whoami.rule=Host(`whoami.earles.io`)
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.tls.certresolver=production
      - traefik.http.routers.whoami.middlewares=authentik@docker
    networks:
      - traefik

  authentik-proxy:
      image: ghcr.io/goauthentik/proxy
      container_name: authentik-proxy
      environment:
        - AUTHENTIK_HOST=https://authentik.internal.earles.io
        - AUTHENTIK_INSECURE=false
        - AUTHENTIK_TOKEN=${AUTHENTIK_TOKEN}
        - AUTHENTIK_HOST_BROWSER=https://auth.earles.io
      #ports:
      #    - 9000:9000
      #    - 9443:9443
      labels:
        traefik.enable: true
        traefik.docker.network: traefik
        traefik.port: 9000
        traefik.http.routers.authentik_whoami.rule: Host(`whoami.earles.io`) && PathPrefix(`/outpost.goauthentik.io/`)
        traefik.http.routers.authentik_bw.rule: Host(`bw.earles.io`) && PathPrefix(`/outpost.goauthentik.io/`)
        traefik.http.routers.authentik_openwebui.rule: Host(`openwebui.earles.io`) && PathPrefix(`/outpost.goauthentik.io/`)
        traefik.http.middlewares.authentik.forwardauth.address: http://authentik-proxy:9000/outpost.goauthentik.io/auth/traefik
        traefik.http.middlewares.authentik.forwardauth.trustForwardHeader: true
        traefik.http.middlewares.authentik.forwardauth.authResponseHeaders: X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version
        restart: unless-stopped
      networks:
       - traefik

networks:
  traefik:
    external: true